//mongeez formatted javascript
//changeset bob:insert-users
db.user.insert({name: 'Atticus'});
db.user.insert({name: 'Blaine'});
db.user.insert({name: 'Caelum'});
db.user.insert({name: 'Damien'});
db.user.insert({name: 'Elspeth'});
db.user.insert({name: 'Freya'});
db.user.insert({name: 'Genesis'});
db.user.insert({name: 'Hermione'});
db.user.insert({name: 'Isadora'});
db.user.insert({name: 'Jared'});
db.user.insert({name: 'Kyla'});
db.user.insert({name: 'Lucia'});
db.user.insert({name: 'Magnus'});
db.user.insert({name: 'Narcissa'});
db.user.insert({name: 'Orion'});
db.user.insert({name: 'Persephone'});
db.user.insert({name: 'Quinn'});
db.user.insert({name: 'Reagan'});
db.user.insert({name: 'Silas'});
db.user.insert({name: 'Thebe'});
db.user.insert({name: 'Uston'});
db.user.insert({name: 'Vada'});
db.user.insert({name: 'Waylin'});
db.user.insert({name: 'Xanthie'});
db.user.insert({name: 'Yvette'});
db.user.insert({name: 'Zephyr'});
